#!/bin/bash
#
# Output public IP from behind NAT using checkip.dyndns.org
#
curl -s http://checkip.dyndns.org/ | cut -d ' ' -f 6 | sed \
s/"body\|html\|<\|>\|\/"//g
#
# Respect for opensource... Respect for sharing!!
# Script written by Sergani ... msergani@gmail.com
